### ISSUE TITLE
testSpecs error

### ISSUE THREAD

**Issue by vadimfrolov** [adjust/react-and-rockets#4]
Iridium NEXT Mission 7 launch year is 2018, not 2019

This is testSpecs.json ↓

![Screenshot 2021-12-05 at 16 45 39](https://user-images.githubusercontent.com/46858187/144749081-bbbe9300-07a6-44f2-b5af-d50f69cf12f2.png)

This is an actual data from SpaceX API ↓

<img width="672" alt="Screenshot 2021-12-05 at 16 48 31" src="https://user-images.githubusercontent.com/46858187/144749184-aa2f110a-ee08-4de7-9a28-c42b4d6e934c.png">

**Comment by vadimfrolov** [comment]
@adjust-frontend-hiring

**Comment by AragonCodes** [comment]
Hi. Thanks for reaching out.

The `json` data was modified on purpose. Thus, It doesn't match the API response.

**Comment by vadimfrolov** [comment]
But if it's the testSpecs they must be the same, right?
